package:
  name: chorus
  version: 0.8.4

source:
  git_rev: v0.8.4
  git_url: ../

requirements:
  build:
    - python
    - cython
    - setuptools

  run:
    - python
    - numpy
    - numexpr
    - matplotlib
    - networkx
    - pyyaml

test:
  imports:
    - chorus

about:
  home: https://github.com/mojaie/chorus
  license: MIT
  license_file: LICENSE
